[build-system]
requires = ["uv_build >= 0.8.17, <1.0.0"]
build-backend = "uv_build"
[project]
name = "hc-term-graph"
version = "1.0.0"
authors = [{name = "strawberry-t"}]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
description = "A CLI tool for displaying simple bar graphs from an equation or a csv file"
readme = "CALC_README.md"
requires-python = ">=3.8"
dependencies = ["argparse>=1.3.0"]
[project.scripts]
termgraph = "hc_term_graph.termgraph:app"
termgraph-calc = "hc_term_graph.termgraph_calc:termgraph_calc_begin"
[tool.uv.build-backend]
module-root = ""